# Generated by Django 5.2 on 2025-04-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('receipt', models.FileField(upload_to='receipts/')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('approved', 'Оплачено'), ('rejected', 'Отменено')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
